### ISSUE TITLE
[runner] json-c 라이브러리 라이센스 관련

### ISSUE THREAD

**Issue by SuhoSon** [I-O-Benchmark-On-Container/ContainerTracer#28]
[json-c 라이브러리의 라이센스](https://github.com/json-c/json-c/blob/master/COPYING)에 아래와 같은 문장이 있습니다.

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

따라서, json-c 라이브러리의 라이센스를 추가해야할 것 같습니다.

**Comment by BlaCkinkGJ** [comment]
관련 내용을 추가 확인해본 결과 라이센스가 MIT 허가서의 일종이라는 것을 확인할 수 있었습니다. [이 링크](https://opensource.org/licenses/MIT)의 MIT 라이센스에서 언급하는 내용과 동일한 내용임을 알 수 있습니다.

해당 라이센스에 대해서 OLIS에서 확인해 본 결과 [링크](https://olis.or.kr/license/Detailselect.do?lId=1006&mapCode=010006)와 같았습니다. 사본을 동봉하면 가장 좋겠지만 현재와 같이 `README.md`에 명시적으로 [링크를 표현](https://github.com/I-O-Benchmark-On-Container/ContainerTracer#%EC%82%AC%EC%9A%A9-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC)한 것으로 대체할 수 있지 않을까 싶습니다.

**Comment by BlaCkinkGJ** [comment]
일단은 닫도록 하겠습니다.
