### ISSUE TITLE
[Runner] Trace replay can send more messages than the set time.

### ISSUE THREAD

**Issue by SuhoSon** [I-O-Benchmark-On-Container/ContainerTracer#60]
I have checked that sometimes trace-replay sends more messages than the set time from the testing program.
It is not a critical problem, but I think it may have the possibility to degrade testing performance.

**Comment by BlaCkinkGJ** [comment]
I checked that if the trace-replay sent additional messages, some value had the negative.

I think that is the point to solve this problem.

**Comment by SuhoSon** [comment]
> I checked that if the trace-replay sent additional messages, some value had the negative.
> 
> I think that is the point to solve this problem.

I will check the `trace_replay.c`
